server:
  port: 9017
spring:
  datasource:
    #url: jdbc:mysql://10.10.10.200:3306/flowable?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    #username: root
    #password: JfAsdf0605
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useSSL=false&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver 驱动5 带cj驱动8需要增加时区配置
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 10
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
  profiles:
    include: jdbc


logging:
  level:
    com.demo.updown.mapper: debug
